# Project information
site_name: Burst Wiki
site_description: The Burstcoin Wiki
site_author: The Burst Apps Team
site_url: https://burst-apps-team.github.io/burst-wiki

# Repository (Commented as it is private)
repo_name: burst-wiki
repo_url: https://github.com/burst-apps-team/burst-wiki

# Theme
theme:
  name: 'material'
  #favicon: assets/img/favicon.ico
  #logo: assets/img/logo.png
  feature:
    tabs: true
  palette:
    primary: blue
    accent: blue

# Options
extra:
  social:
    - type: github-alt
      link: https://github.com/harry1453

# Page tree
pages:
  - English:
    - Home: en/index.md
    - 500k HF Checklist: en/500k-hf-checklist.md
    - Activate Burst Account: en/activate-burst-account.md
    - Alias System: en/alias-system.md
    - Arbitrary Messages: en/arbitrary-messages.md
    - Asset Exchange: en/asset-exchange.md
    - Automated Transaction: en/automated-transaction.md
    - Block Reward: en/block-reward.md
    - BlockTalk: en/BlockTalk.md
    - BRS Configuration File: en/brs-default-properties-configuration-file.md
    - BRS Docker Installation: en/brs-docker-installation.md
    - BRS Linux Installation: en/brs-linux-installation.md
    - BRS MacOS Installation: en/brs-macos-installation.md
    - BRS Windows Installation: en/brs-windows-installation.md
    - Burst Blockchain: en/burst-blockchain.md
    - Burstcoin Reference Software: en/burst-reference-software.md
    - Burst Services: en/burst-services.md
    - Burst Software: en/burst-software.md
    - Burst Support for ERC20 tokens: en/burst-support-for-erc20-tokens.md
    - Burst Who's Who: en/burst-who-s-who.md
    - Burst Wiki: en/burst-wiki.md
    - CIP: en/cip.md
    - Colored Coins: en/colored-coins.md
    - Current Features: en/current-features.md
    - Engraver - How to compile from source: en/engraver---how-to-compile-from-source.md
    - Exchanges: en/exchanges.md
    - FAQ: en/faq.md
    - Getting Started: en/getting-started.md
    - History of Burst: en/history-of-burst.md
    - Internal AT and Escrow Account: en/internal-at-and-escrow-account.md
    - Join Us: en/join-us-.md
    - List of Burst Related Websites: en/list-of-burst-related-websites.md
    - List of International Burst Websites: en/list-of-international-burst-websites.md
    - MacOS Burst Wallet Installation: en/macos-burst-wallet-installation.md
    - Marketplace: en/marketplace.md
    - Mining: en/mining.md
    - Mobile App: en/mobile-app.md
    - Mortimer: en/mortimer.md
    - NXT default properties configuration file: en/nxt-default-properties-configuration-file.md
    - Offline Transaction Signing: en/offline-transaction-signing.md
    - Pchains: en/pchains.md
    - Plotting Software: en/plot-software.md
    - Plotter: en/plotter.md
    - Plotting: en/plotting.md
    - PoCC Mobile App: en/pocc-mobile-app.md
    - Proof of Capacity: en/proof-of-capacity.md
    - Publications - Burst Cryptocurrency News: en/publications--burst--cryptocurrency-news-.md
    - Publications - Burst Gneral: en/publications--burst--general-.md
    - Publications - Burst Commercial: en/publications-burst-commercial-.md
    - Publications - Burst Cryptonews: en/publications-burst-cryptonews-.md
    - Publications - Burst News: en/publications-burst-news-.md
    - Publications - Burst Research: en/publications-burst-research-.md
    - Publications - Burst: en/publications-burst.md
    - Qbundle: en/qbundle.md
    - Reward Assignment: en/reward-assignment.md
    - RS Address Format: en/rs-address-format.md
    - Scavenger - How to compile from source: en/scavenger---how-to-compile-from-source.md
    - Secure your Burst: en/secure-your-burst.md
    - Slot-Based Transaction Fees: en/slot-based-transaction-fees.md
    - Smart Contract: en/smart-contract.md
    - Softfork Wishlist: en/softfork-wishlist.md
    - Style Guide: en/style-guide.md
    - Team Applications: en/team-applications.md
    - Team Support: en/team-support.md
    - Technical Information about Mining and Block Forging: en/technical-information-about-mining-and-block-forging.md
    - Technical Information to create plot files: en/technical-information-to-create-plot-files.md
    - Testnet: en/testnet.md
    - The Burst API: en/the-burst-api.md
    - The Burst API Examples: en/the-burst-api-examples.md
    - TODO: en/todo.md
    - Transaction and Fee Types: en/transaction-and-fee-types.md
    - Whitepapers: en/whitepaper-burst.md
    - Wikipedia - Burstcoin: en/wikipedia-burstcoin.md
  - Français:
    - Page d’accueil: fr/index.md
    - Caractéristiques actuelles: fr/current-features.md
    - Marché: fr/marketplace.md
    - QBundle: fr/qbundle.md
  - Deutsche:
    - Homepage: de/index.md
    - Aktuelle Funktionen: de/current-features.md
    - Alias-System: de/alias-system.md
    - Marktplatz: de/marketplace.md
  - Português:
    - Pagina inicial: pt-br/index.md
    - QBundle: pt-br/qbundle.md
  - Росси́я:
    - домашняя страница: ru/index.md
    - текущие функции: ru/current-features.md
    - Burst Wiki: ru/burst-wiki.md
  - 中文維基百科:
    - 主頁: zh-hant/index.md
    - 時尚指南: zh-hant/style-guide.md
